autoInstallPeers: true
overrides:
  fastify: 5.12.4
allowBuilds:
  '@parcel/watcher': true
  nx: true
  unrs-resolver: true
  "@nestjs/core": false
  esbuild: false
  '@prisma/engines': true
  prisma: true
  bcrypt: false
